---
services:
  app:
    build: 
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend
    restart: unless-stopped
  db:
    image: mongo:6
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    restart: unless-stopped
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped
networks:
  backend:
    driver: bridge
volumes:
  db_data: